### PR TITLE
implement gokit logger interface to SugaredLogger

### PR DESCRIPTION
**Pull request by alex-laties**
Implements the proposal in #635

### CODE REVIEW

**Comment by alex-laties** [comment]
um... I've signed the CLA... how do I get that CLAssistant bot to post that here?

**Comment by abhinav** [comment]
I see a couple issues with putting this directly on SugaredLogger:

- Log is a very generic name. For people using Zap directly, it adds no value.
  If this adapter was provided by Zap, it would probably need to be a function
  similar `ToGoKit(*Logger) *GoKitLogger`.
- The empty message is a bit of a problem. I imagine codebases have some
  convention around which field in their go-kit `Log` is the message, i.e.
  `log.Log("msg", "did something", [other keys])`. Ideally, the Zap-based
  implementation of `go-kit/log.Logger` is aware of this key and pulls the
  key-value pair out of `keyvals` if found. Further, because the key probably
  varies between projects, this would need to be configurable. This is quite a
  lot of logic that definitely does not belong on the SugaredLogger itself,
  and possibly not in Zap at all.

My recommendation is to create a separate standalone library out of this
functionality. That avoids zap or go-kit taking dependencies on each other and
lets you version that library separately.

**Comment by alex-laties** [comment]
@abhinav both are very sound points.

Regarding the message field in go-kit... there really is no standard, so `msg, message`, and any other variation of letters may be valid. Really depends on the org. I absolutely agree that the logic to extract and uplift those things should be outside of the `SugaredLogger`.

I think you're recommendation to create a bridging library is a good one.
I'll try it out.

Thanks!

**Comment by bjm88** [comment]
@alex-laties hi - did you ever do that?  could share the link?

we having this compile issue

	*zap.SugaredLogger does not implement logger.Interface (missing Fatalln method)

just want to pass the logger to another library

**Comment by alex-laties** [comment]
@bjm88 yep! https://github.com/alex-laties/gokitzap.

**Pull request closed without merging**
