### PR TITLE
Fix bug for Issue: #554 MapObjectEncoder does not match jsonEncoder

### PR DESCRIPTION
**Pull request by sammyrnycreal**
Fix bug

[MapObjectEncoder does not match jsonEncoder](https://github.com/uber-go/zap/issues/554) #554 

 Problem was that new openNamespaces that are created during AppendObject() call were not closed.

 Note, ONLY new openNamespaces that are created during AppendObject() are closed. If they were created at prior to AppendObject() call, it will remain open till EncodeEntry() call completes.

- `make all` passes all test.

@jkanywhere This will resolve the issue you raised. I included the test you wrote up [here](https://github.com/jkanywhere/zap/tree/encoder-namespace-bug) Thank you, that helped me find the bug.

### CODE REVIEW

**Comment by sammyrnycreal** [comment]
Hi @abhinav Do you know whom I can ping to get this PR reviewed and merged in?

**Comment by abhinav** [comment]
@sammyrnycreal Thanks for the fix and apologies for the delay!
We'll have someone look at this soon.

Internal issue ref: GO-987

**Review by abhinav — APPROVED** [review]
LGTM. Thanks for the fix @sammyrnycreal!

**Review by sywhang — APPROVED** [review]
LGTM

**Comment by abhinav** [comment]
Thanks again, @sammyrnycreal!

**Comment by sammyrnycreal** [comment]
@abhinav Anytime.

**Pull request merged**
