### PR TITLE
change fmt.Sprint to fmt.Sprintln

### PR DESCRIPTION
**Pull request by FH0**
https://github.com/uber-go/zap/issues/889

### CODE REVIEW

**Review by abhinav — CHANGES_REQUESTED** [review]
This constitutes a breaking change. We strongly prefer to avoid a breaking change.

Perhaps we can add `*ln` variants of methods to the SugaredLogger: Infoln, Warnln, and so on.

**Comment by alxn** [comment]
Also logging typically doesn't need to be terminated with a new line.

**Comment by FH0** [comment]
> This constitutes a breaking change. We strongly prefer to avoid a breaking change.
> 
> Perhaps we can add `*ln` variants of methods to the SugaredLogger: Infoln, Warnln, and so on.

ok

**Comment by FH0** [comment]
> Also logging typically doesn't need to be terminated with a new line.

The goal is to automatically add spaces. Check out the issue I mentioned.

**Pull request closed without merging**
