### PR TITLE
Add New Trace Logging Level

### PR DESCRIPTION
**Pull request by LeviMatus**
A few people have expressed interest in having a TraceLevel added to Zap (Some mention of this in #680 and again in #747). This PR addresses that interest by introducing this logging level.

### CODE REVIEW

**Comment by prashantv** [comment]
I'm not sure that we can add a level to zap 1.0 and retain backwards compatibility. Existing cores, hooks, etc do not know about the trace level and may not handle it properly. For example, here's an adapter library that checks for known levels:

https://github.com/uber-common/bark/blob/master/zbark/zapify.go#L64

That library at least handles it will by returning an error, but there may be other cases where it panics.

I don't think we can add any new levels unless we do a zap 2.0.

**Comment by LeviMatus** [comment]
Thanks for the code reference there to check against. Having external wrappers is something I had not thought of and is a great point. I see now how this could make introducing new levels more difficult.

Moreover, I realized that I forgot to add Trace methods to `sugar.go`, so the PR can't even be considered complete at this time.

**Comment by novabyte** [comment]
@LeviMatus You've done great work on this pull request! It's sorely needed within Zap even if we cannot specify our own set of severity levels for output.

@prashantv Is there any kind of timeline for when a set of changes like this would be acceptible to the release constraints of Zap?

**Comment by prashantv** [comment]
> @prashantv Is there any kind of timeline for when a set of changes like this would be acceptible to the release constraints of Zap?

We don't currently have a timeline for zap 2.0, but the improvements we'd like to make in a 2.0 are tracked here: #388.

We don't currently have a concrete timeline for a 2.0 though.

**Comment by se3000** [comment]
Any update on this? We would like to use it.

**Comment by Antonboom** [comment]
What's the bottom line? Wait for zap v2?

**Comment by prashantv** [comment]
We definitely can't add it in 1.0. It's possible for 2.0, but that's not in the roadmap. At that point, we'd want to consider the cost/benefit (it's added cognitive overhead to add another level, so we should ensure there's a significant benefit).

Closing for 1.0.

**Pull request closed without merging**
