### PR TITLE
Ignore Sync errors

### LINKED ISSUE #328: write error: sync /dev/stdout: invalid argument
Thanks for opensourcing this library!

Everything is fine during program execution, but when the application shuts down (due to an error) zap logs to stderr: `write error: sync /dev/stdout: invalid argument`

Output:
```
2017-02-20T17:25:14.708+0100	info	starting
2017-02-20T17:25:14.708+0100	info	publishing	{"port": 8080}
2017-02-20T17:45:54.522+0100	fatal	Error publishing the API	{"error": "listen tcp :8080: bind: address already in use"}
2017-02-20 17:25:14.708574765 +0100 CET write error: sync /dev/stdout: invalid argument
exit status 1
```

Relevant set-up code:
```
config.FileLoggingEnabled = false
config.EncodeLogsAsJson = false
...
encCfg := zapcore.EncoderConfig{
	TimeKey:        "@timestamp",
	LevelKey:       "level",
	NameKey:        "logger",
	CallerKey:      "caller",
	MessageKey:     "msg",
	StacktraceKey:  "stacktrace",
	EncodeLevel:    zapcore.LowercaseLevelEncoder,
	EncodeTime:     zapcore.ISO8601TimeEncoder,
	EncodeDuration: zapcore.NanosDurationEncoder,
}
...
func Configure() {
	writers := []zapcore.WriteSyncer{os.Stdout}
	if config.FileLoggingEnabled {
		writers = append(writers, newRollingFile(....))
	}
        GlobalLogger = newZapLogger(config.EncodeLogsAsJson, zapcore.NewMultiWriteSyncer(writers...))
}

func newZapLogger(encodeAsJSON bool, output zapcore.WriteSyncer) *zap.Logger {
	encoder := zapcore.NewConsoleEncoder(encoderCfg)
	if encodeAsJSON {
		encoder = zapcore.NewJSONEncoder(encoderCfg)
	}
	return zap.New(zapcore.NewCore(encoder, output, zap.NewAtomicLevel()))
}
```

### PR DESCRIPTION
**Pull request by Ulexus**
Take the simplest approach to fixing the cross-platform compatibility issues with syncing stderr and stdout (outlined in #328) and just ignore sync errors. If we come up with a clean solution to #370, we can revert this change.

Fixes #328.

### CODE REVIEW

**Comment by peter-edge** [comment]
I'm not sure just ignoring a sync error is the best way to go about this - any other ideas?

**Comment by akshayjshah** [comment]
I'm going to push some commits to take this PR in a different (simpler) direction. However, we really appreciate the time you've taken on this - I'll make sure to preserve your authorship of the changes.

**Comment by Ulexus** [comment]
Yeah, sorry I haven't had time to work on this more.  If you've a better idea, please take it where you want!

**Comment by akshayjshah** [comment]
No worries at all - appreciate the work that you've already put in!

**Pull request merged**
