### PR TITLE
syslog writer

### PR DESCRIPTION
**Pull request by avidak**
This commit allows zap to write log in syslog writer

### CODE REVIEW

**Comment by akshayjshah** [comment]
Thank you for the PR, @avidak! I probably won't have a chance to review it until next week.

**Comment by jeffbean** [comment]
This PR is useful for a project I'm working on. 

Just a friendly ping.

**Comment by lafolle** [comment]
We're also waiting for this to merge.

Just another friendly ping :)

**Comment by akshayjshah** [comment]
Thank you for the effort you put into this PR, @avidak!

I've added a comment to the discussion on #96, which I won't repeat in full here. The short version is that the zap maintainers (including me) don't understand syslog well enough to support this code, so we'd prefer to keep it in a separate extension package that's owned by someone with more expertise.

I'm going to close this PR - let's continue the discussion #96 instead.

**Pull request closed without merging**
