### PR TITLE
Add support for uint32

### PR DESCRIPTION
**Pull request by higebu**
Before opening your pull request, please make sure that you've:
- [x] [signed Uber's Contributor License Agreement](https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform);
- [x] added tests to cover your changes;
- [x] run the test suite locally (`make test`); and finally,
- [x] run the linters locally (`make lint`).

Thanks for your contribution!

### CODE REVIEW

**Comment by prashantv** [comment]
Thanks for your contribution @higebu!

I'm not sure whether we should add support for `uint32` on top of `uint64`. We have the following options for signed integers: `zap.Int` and `zap.Int64`.

For users of `int32`, they can use either `zap.Int` or `zap.Int64` with a cast, and the same is true for `uint32` with `zap.Uint` or `zap.Uint64`.

Technically only `zap.Int64` is required, but since the most common integer type is likely `int`, it made sense to provide `zap.Int` as a helper for common use cases.

Would like to hear other people's thoughts on keeping the API small vs making it easier to use in more use cases. cc @abhinav @akshayjshah

**Comment by higebu** [comment]
@prashantv Thank you for your comment.

I know we can use zap.Int64 for uint32 with a cast. Feel free to merge or reject this PR.

**Comment by maverickwoo** [comment]
>Would like to hear other people's thoughts on keeping the API small vs making it easier to use in more use cases.

I advocate supporting every type in the `builtin` package because these types are part of the Go language and it seems reasonable for users of a logging library to expect the library to support all built-in types.

**Comment by akshayjshah** [comment]
For now, I'd also prefer to keep the API as small as is practical. I'm going to close this, but we'll reconsider expanding our type support once the rest of the API is more stable.

**Pull request closed without merging**
