### PR TITLE
Group similar benchmarks together

### PR DESCRIPTION
**Pull request by billf**

### CODE REVIEW

**Comment by billf** [comment]
```
$ go test -benchmem -bench . ./benchmarks/...
testing: warning: no tests to run
BenchmarkAddingFields/apexLog-8        	  100000       	     15041 ns/op       	    4026 B/op  	      64 allocs/op
BenchmarkAddingFields/goKit-8          	  500000       	      4562 ns/op       	    3654 B/op  	      71 allocs/op
BenchmarkAddingFields/log15-8          	  100000       	     19903 ns/op       	    5344 B/op  	      91 allocs/op
BenchmarkAddingFields/logrus-8         	  300000       	      6104 ns/op       	    5733 B/op  	      77 allocs/op
BenchmarkAddingFields/zapBarkify-8     	  500000       	      2917 ns/op       	    3623 B/op  	      23 allocs/op
BenchmarkAddingFields/zapDisabledLevels-8              	10000000       	       236 ns/op       	     704 B/op  	       2 allocs/op
BenchmarkAddingFields/zapDisabledLevelsCheck-8         	500000000      	         3.79 ns/op    	       0 B/op  	       0 allocs/op
BenchmarkAddingFields/zapSample-8                      	 3000000       	       357 ns/op       	     704 B/op  	       2 allocs/op
BenchmarkAddingFields/zapSampleCheck-8                 	20000000       	        65.6 ns/op     	       0 B/op  	       0 allocs/op
BenchmarkAddingFields/zap-8                            	 1000000       	      1039 ns/op       	     707 B/op  	       2 allocs/op
BenchmarkWithoutFields/apexLog-8                       	  500000       	      3395 ns/op       	     584 B/op  	      11 allocs/op
BenchmarkWithoutFields/goKit-8                         	 2000000       	       858 ns/op       	     672 B/op  	      14 allocs/op
BenchmarkWithoutFields/log15-8                         	  300000       	      5087 ns/op       	    1479 B/op  	      24 allocs/op
BenchmarkWithoutFields/logrus-8                        	 1000000       	      1851 ns/op       	    1322 B/op  	      25 allocs/op
BenchmarkWithoutFields/standardLibrary-8               	 3000000       	       746 ns/op       	      32 B/op  	       2 allocs/op
BenchmarkWithoutFields/zapBarkify-8                    	 5000000       	       341 ns/op       	      40 B/op  	       3 allocs/op
BenchmarkWithoutFields/zapDisabledLevels-8             	300000000      	         5.11 ns/op    	       0 B/op  	       0 allocs/op
BenchmarkWithoutFields/zapStandardize-8                	 3000000       	       410 ns/op       	      40 B/op  	       3 allocs/op
BenchmarkWithoutFields/zapDisabledLevelsCheck-8        	 3000000       	       359 ns/op       	      40 B/op  	       3 allocs/op
BenchmarkWithoutFields/zapSample-8                     	 5000000       	       339 ns/op       	      40 B/op  	       3 allocs/op
BenchmarkWithoutFields/zapSampleCheck-8                	20000000       	        71.8 ns/op     	       0 B/op  	       0 allocs/op
BenchmarkWithoutFields/zap-8                           	 5000000       	       260 ns/op       	       0 B/op  	       0 allocs/op
BenchmarkWithAccumulatedContext/apexLog-8              	  100000       	     18440 ns/op       	    2803 B/op  	      49 allocs/op
BenchmarkWithAccumulatedContext/goKit-8                	  300000       	      5995 ns/op       	    2938 B/op  	      49 allocs/op
BenchmarkWithAccumulatedContext/log15-8                	   50000       	     20833 ns/op       	    4681 B/op  	      70 allocs/op
BenchmarkWithAccumulatedContext/logrus-8               	  200000       	      6451 ns/op       	    3923 B/op  	      61 allocs/op
BenchmarkWithAccumulatedContext/zapBarkify-8           	 5000000       	       358 ns/op       	      48 B/op  	       3 allocs/op
BenchmarkWithAccumulatedContext/zapDisabledLevels-8            	300000000      	         4.69 ns/op    	       0 B/op  	       0 allocs/op
BenchmarkWithAccumulatedContext/zap-8                          	10000000       	       248 ns/op       	       0 B/op  	       0 allocs/op
PASS
ok     	github.com/uber-go/zap/benchmarks      	55.821s
```

**Comment by billf** [comment]
whoops, didn't realize this was a 1.7-only feature.

**Comment by akshayjshah** [comment]
It is pretty awesome, though.

**Comment by billf** [comment]
deferring is fine or i also whipped up https://gist.github.com/billf/16223862176bdc6ec302c7cb9e8fc213 as a hack.

**Comment by akshayjshah** [comment]
I'd rather defer this for another 3 months.

**Comment by akshayjshah** [comment]
Getting close to 1.8 (finally), but probably not worth trying to rebase this change onto the wildly-different dev branch.

**Pull request closed without merging**
