### PR TITLE
Use runtime.CallersFrames

### PR DESCRIPTION
**Pull request by peter-edge**
Just doing https://github.com/uber-go/zap/issues/354

### CODE REVIEW

**Comment by prashantv** [comment]
Can you post a summary of any differences in the benchmark results from switching to `CallerFrames`? Just curious what kind of performance penalty we're paying (if any).

**Comment by akshayjshah** [comment]
The relevant benchmark here is `BenchmarkStackField`.

**Comment by peter-edge** [comment]
```
# master
BenchmarkStackField-8   	 1000000	      1032 ns/op	     449 B/op	       2 allocs/op
# runtime-frames
BenchmarkStackField-8   	 1000000	      1008 ns/op	     449 B/op	       2 allocs/op
```

no change it seems like

**Comment by akshayjshah** [comment]
The escape analyzer has our back here - even though CallerFrames returns a reference, it doesn't escape and so we're not penalized.

**Pull request merged**
