### PR TITLE
test: migrate slog benchmark from golang.org/x/exp/slog to log/slog

### PR DESCRIPTION
**Pull request by chenyanchen**
Bechmark test `log/slog`.

### CODE REVIEW

**Comment by chenyanchen** [comment]
Did you have uniform benchmark environment? If you do, please update benchmark result in README.

**Review by abhinav — COMMENTED** [review]
Hey, @chenyanchen. Thanks for this PR. This makes sense, and .

However, I think this could benefit from a small change:
What you've done in `b.Run("slog"` is great.
I think we need a second `b.Run("slog/LogAttrs"` that is the same, except it uses [Logger.LogAttrs](https://pkg.go.dev/log/slog#Logger.LogAttrs) and the old `fakeSlogFields()` list.
This will provide a comparison of both, slog with `any`, and slog with `slog.Attr`.

Would you be willing to make that change?
If not, one of us will try to get to it as soon as we have some time to do it.

**Comment by chenyanchen** [comment]
It's very thoughtful of you.

The `slog` `Logger.LogAttrs` benchmark been added.

**Comment by chenyanchen** [comment]
> Did you have uniform benchmark environment? If you do, please update benchmark result in README.

If you do not ask for specific hardware, I can do benchmarks on my `M1` Mac.

**Comment by abhinav** [comment]
> > Did you have uniform benchmark environment? If you do, please update benchmark result in README.
> 
> If you do not ask for specific hardware, I can do benchmarks on my `M1` Mac.

Hey, we do not have a uniform benchmark environment.
The benchmarks are updated with whatever machine someone was on at the time they ran the benchmarks.
It hasn't been a problem because the absolute numbers are less important than the relative numbers, which tend to follow the same trend regardless of where we're running the benchmarks.

**Comment by chenyanchen** [comment]
Benchmars has been updated. The results looks as expected.

**Review by abhinav — APPROVED** [review]
It's weird that there's no difference between slog with any and slog with LogAttrs, but that's something to investigate later.

Thanks!

**Pull request merged**
