### PR TITLE
Optimize the process of getting/putting a jsonEncoder from/to _jsonPool

### PR DESCRIPTION
**Pull request by tylitianrui**
Any item stored in the Pool may be removed automatically at any time without notification.  it will  be better ，if  the process of getting/putting a jsonEncoder is modified.

### CODE REVIEW

**Comment by prashantv** [comment]
Thanks for the contribution @tylitianrui 

Would you be able to explain the reasoning a little more, I wasn't able to follow the advantage of setting fields in get vs put.

**Comment by tylitianrui** [comment]
a jsonEncoder  stored in   _jsonPool  may  not  be  used becase of  GC.  if  a  jsonEncoder were  put   into  _jsonPool just   before  GC. IT would be removed  instead of reused.  Resetting  the   jsonEncoder  , when  Putting  into  _jsonPool,   is  unnecessary.   Resetting   jsonEncoder , when getting from _jsonPool,   it is  better.

**Comment by prashantv** [comment]
> a jsonEncoder stored in _jsonPool may not be used becase of GC. if a jsonEncoder were put into _jsonPool just before GC. IT would be removed instead of reused. Resetting the jsonEncoder , when Putting into _jsonPool, is unnecessary. Resetting jsonEncoder , when getting from _jsonPool, it is better.

Thanks for the details. There's a couple of additional considerations as well:
 * For performance, we only need to reset for "dirty" objects, but now it resets even for new encoders.
 * Resetting the object as part of put makes it more likely that misuses are detected.

The misuse detection is especially useful for correctness, so before we change this, I'd like to see what sort of performance improvement this approach leads to.

**Comment by tylitianrui** [comment]
thanks. I agree with you.

**Pull request closed without merging**
